version: 2
jobs:
  build:
    machine: true
    steps:
      - run: cat $HOME/.bashrc
      - run: rvm get stable --auto-dotfiles
      - run: ruby -v
      - run: echo 2.3.4 >> .ruby-version
      - run: ruby -v


workflows:
  version: 2
  build:
    jobs:
      - build


