version: 2
jobs:
  build:
    machine: true
    steps:
      - run: rvm install 2.3.4
      - run: echo 2.3.4 >> .ruby-version
      - run: |
             source $(rmv env --path)
             ruby -v
      - run: . $(rmv env --path) >> $BASH_ENV
      - run: ruby -v
      - run: echo 2.3.4 >> .ruby-version
      - run: ruby -v
      - run: source $(rvm env --path)
      - run: ruby -v
      - run: 
          shell: /bin/bash --login -eo pipefail
          command: rvm list ; which ruby
             
workflows:
  version: 2
  build:
    jobs:
      - build


