version: 2
jobs:
  build:
    machine: true
    steps:
      - run: cat $HOME/.bashrc
      - run: rvm get stable --auto-dotfiles
      - run: ruby -v
      - run: echo 2.3.4 >> .ruby-version
      - run: ruby -v
      - run: rvm install 2.3.4
      - run: rvm use 2.3.4 --default
      - run: ruby -v
      - run: 
          shell: /bin/bash --login -eo pipefail
          command: rvm list ; which ruby
             
workflows:
  version: 2
  build:
    jobs:
      - build


