version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: |
             echo "[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm"" >> $HOME/.bash_profile
             cat $HOME/.bashrc
             rvm install 2.3.4
             rvm get stable --auto-dotfiles
             bash -l -c "rvm use 2.3.4 --install --create"
             ruby -v


workflows:
  version: 2
  build:
    jobs:
      - build
