version: 2
jobs:
  build:
    machine: true
    steps:
      - run: cat $HOME/.bashrc
      - run: rvm install 2.3.4
      - run: rvm get stable --auto-dotfiles
      - run: bash -l -c "rvm use 2.3.4 --install --create"
      - run: cat $HOME/.bashrc
      - run: ruby -v


workflows:
  version: 2
  build:
    jobs:
      - build


