version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: rvm install 2.3.4
      - run: bash -l -c "rvm use 2.3.4"
      - run: bash -l -c "ruby -v"


workflows:
  version: 2
  build:
    jobs:
      - build
