version: 2
jobs:
  build:
    machine: true
    steps:
#     - checkout
      - run: sed -i "1i[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm"" $HOME/.bashrc
      - run: export PATH="$PATH:/opt/circleci/.rvm/bin"
      - run: cat $HOME/.bashrc
      - run: rvm install 2.3.4
      - run: rvm get stable --auto-dotfiles
      - run: bash -l -c "rvm use 2.3.4 --install --create"
      - run: cat $HOME/.bashrc
      - run: ruby -v


workflows:
  version: 2
  build:
    jobs:
      - build
